= Minikube Tutorial
:docinfo: shared
:!toc:

My personal Minikube tutorial.

[discrete]
==== Table of Contents
====
<1> link:./01-prerequisites.adoc[Prerequisites]
<2> link:./02-installation.adoc[Installation]
<3> link:./03-start-minikube.adoc[Start Minikube]
<4> link:./manifests/README.adoc[Reference Manifests]
<5> link:./05-deploy-application.adoc[Deploy Application]
<6> link:./06-get-minikube-ip-and-service-endpoints.adoc[Get Minikube IP and Service Endpoints]
<7> link:./07-nodeport.adoc[Access Nodeport on Minikube]
<8> Create Persistent Volumes
<9> Create Dynamic Volumes
<10> Minikube Addons
<11> Minikube Dashboard
<12> Custom CPU and RAM Resources
<13> Multiple Clusters using Profiles
<14> Multi-node Cluster
<15> Alternatives
<16> FAQ
<17> link:./knative/00-install-knative-minikube.adoc[Knative]
<18> Istio
<19> IntelliJ Plugins
<20> VSCode Plugins
<21> Kubectl
<22> Helm
<23> Alternative - Docker Compose
<24> Alternative - Podman
====

[discrete]
==== Reference Source Material
I have used several sources for my personal tutorial and several of these may not be Minikube specifically, yet have very good Minikube information or instructions.

[.stripes-even, %header, cols="1, 1"]
|===
| *Source* | *Author*
|https://minikube.sigs.k8s.io/docs/handbook/[Minikube Handbook]
|Minikube sig
|https://devopscube.com/kubernetes-minikube-tutorial/[Kubernetes Minikube Tutorial]
|Bibin Wilson
|https://redhat-scholars.github.io/kubernetes-tutorial/kubernetes-tutorial/installation.html[Kubernetes Tutorial]
|Red Hat Developer
|https://github.com/csantanapr/knative-minikube[knative-minikube]
|Carlos Santana
|===
