= Setting Up Knative on Minikube
:docinfo: shared

Setup Minikube to run Knative Serving

https://github.com/csantanapr/knative-minikube[Source: Carlos Santana knative-minikube]

TLDR;

----
minikube start
minikube tunnel
----

== Configure And Start Minikube

Versions used:
====
.At the time of writing June 2022
<1> Knative Serving 1.3.0
<2> Knative Kourier 1.3.0
<3> Knative Eventing 1.1.4
<4> Minikube 1.25.2
<5> Kubernetes 1.22.2
====

=== Configuration
Minikube Configuration
----
minikube config set cpus 6
minikube config set memory 16384
minikube config set kubernetes-version v1.22.2
minikube config set container-runtime containerd
----

=== Tools for Kubernetes

[NOTE]
All of the MacOS downloads are *amd* links.  If you have a newer Mac, link to the
releases for that tool.

[.stripes-even, %header, cols="1,1,1"]
|===
|*Tool* | *Mac* | *Fedora*
|Git
|https://git-scm.com/download/mac[Download]
|dnf install git
|kubectl
|https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/darwin/amd64/kubectl[Download]
|https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl[Download]
|https://github.com/wercker/stern[stern]
|brew install stern
|Although you can install stern through a direct download, I have found, it will probably not work
correctly on Linux with minikube.  The easiest way to get it working is to install a kubectl
plugin called https://krew.sigs.k8s.io/docs/user-guide/setup/install/[krew] first.
Then install stern via krew:

kubectl krew install stern
|https://github.com/mikefarah/yq[yq]
|https://github.com/mikefarah/yq/releases/download/2.4.1/yq_darwin_amd64[Download]
|https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64[Download]
|https://httpie.org/[httpie]
|brew install httpie
|dnf install httpie
|https://github.com/rakyll/hey[hey]
|brew install hey
|https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64[Download]
|kubectx and kubens
|brew install kubectx
|https://github.com/ahmetb/kubectx[Can be downloaded as a bash script or as a plugin for krew]
|watch
|brew install watch
|dnf install procps-ng
|kapp
|
brew tap vmware-tanzu/carvel

 brew install kapp

 kapp version
| https://carvel.dev/kapp/docs/v0.49.0/install/[kapp install]
|ytt
|
brew tap vmware-tanzu/carvel

brew install ytt

ytt version
| https://carvel.dev/ytt/docs/v0.41.0/install/[ytt install]
|===

=== Clean And Check Minikube

If you want to make sure you are using a clean environment, you should first delete the VM:

----
minikube delete
----

If you aren't sure you are running the latest version of minikube:

----
minikube update-check
----

If you don't have the latest version of minikube and wish to update:

link:../upgrade/minikube-upgrade.sh[Update Minikube Bash Script]

=== Start Minikube
Now we can start minikube:
----
minikube start
----

Alternatively, we can use our local bash script:

file:///./bin/start-minikube.sh[Start minikube Bash Script]

After starting minikube, you will need an EXTERNAL-IP for Kourier.  In another terminal window:

----
minikube tunnel
----

=== Deploy Registry

----
minikube -p knativesandbox addons enable registry
----

== Installer Options

=== Install Using *kapp* and *ytt*

link:./install-knative.sh[Install Bash Script]

=== Install Knative Serving using *kubectl*

link:./01-serving.adoc[Install Knative Serving]

=== Install Knative Eventing using *kubectl*

link:./02-eventing.adoc[Install Knative Eventing]
