= Setting Up Knative Serving on Minikube
:docinfo: shared

== Install Knative Serving

[arabic, start=1]
. Set the version of Knative Serving. Latest versions listed above.
+
----
export KNATIVE_SERVING_VERSION="x.x.x"
----
. Install Knative Serving into namespace `knative-serving`
+
----
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v${KNATIVE_VERSION}/serving-crds.yaml
kubectl wait --for=condition=Established --all crd

kubectl apply -f https://github.com/knative/serving/releases/download/knative-v${KNATIVE_VERSION}/serving-core.yaml

kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n knative-serving > /dev/null
----
. Select the version of Knative Net Kourier to install
+
----
 export KNATIVE_NET_KOURIER_VERSION="x.x.x"
----
. Install Knative Layer kourier in namespace `kourier-system`
+
----
kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-v${KNATIVE_NET_KOURIER_VERSION}/kourier.yaml

kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n kourier-system

kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n knative-serving
----
. Set the environment variable `EXTERNAL_IP` to External IP Address of the Worker Node, you might need to run this command multiple times until service is ready.
+
----
EXTERNAL_IP=$(kubectl -n kourier-system get service kourier -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo EXTERNAL_IP=$EXTERNAL_IP
----
. Set the environment variable `KNATIVE_DOMAIN` as the DNS domain using `nip.io`
.. Set the environment variable
+
----
KNATIVE_DOMAIN="$EXTERNAL_IP.nip.io"
echo KNATIVE_DOMAIN=$KNATIVE_DOMAIN
----

.. Double check DNS is resolving
+
----
dig $KNATIVE_DOMAIN
----

. Configure DNS for Knative Serving
+
----
kubectl patch configmap -n knative-serving config-domain -p "{\"data\": {\"$KNATIVE_DOMAIN\": \"\"}}"
----

. Configure Knative to use Kourier
+
----
kubectl patch configmap/config-network \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"ingress.class":"kourier.ingress.networking.knative.dev"}}'
----

. Verify that Knative is Installed properly all pods should be in `Running` state and our `kourier-ingress` service configured.
+
----
kubectl get pods -n knative-serving
kubectl get pods -n kourier-system
kubectl get svc  -n kourier-system
----

=== Deploy Knative Serving Application

. Deploy a sample app
.. Using the https://github.com/knative/client[kn] client
+
----
kn service create hello \
--image gcr.io/knative-samples/helloworld-go \
--port 8080 \
--env TARGET=Knative
----

.. *Optional:* Deploy a Knative Service using the equivalent yaml manifest:
+
----
cat <<EOF | kubectl apply -f -
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Knative"
EOF
----

. Wait for Knative Service to be Ready
+
----
kubectl wait ksvc hello --all --timeout=-1s --for=condition=Ready
----

. Get the URL of the new Service
+
----
SERVICE_URL=$(kubectl get ksvc hello -o jsonpath='{.status.url}')
echo $SERVICE_URL
----

. Test the App
+
----
curl $SERVICE_URL
----
.. The output should be
+
----
Hello Knative!
----

. Check the knative pods that scaled from zero
+
----
kubectl get pod -l serving.knative.dev/service=hello
----

.. The output should be
+
----
NAME                                     READY   STATUS    RESTARTS   AGE
hello-r4vz7-deployment-c5d4b88f7-ks95l   2/2     Running   0          7s
----

.. Try the service `url` on your browser (command works on linux and macos)
+
----
open $SERVICE_URL
----

. You can watch the pods and see how they scale down to zero after http traffic stops to the url
+
----
kubectl get pod -l serving.knative.dev/service=hello -w
----

.. The output should look something like this
+
----
NAME                                     READY   STATUS
hello-r4vz7-deployment-c5d4b88f7-ks95l   2/2     Running
hello-r4vz7-deployment-c5d4b88f7-ks95l   2/2     Terminating
hello-r4vz7-deployment-c5d4b88f7-ks95l   1/2     Terminating
hello-r4vz7-deployment-c5d4b88f7-ks95l   0/2     Terminating
----

. If we try to access the url again, and you will see a new pod running again.
+
----
NAME                                     READY   STATUS
hello-r4vz7-deployment-c5d4b88f7-rr8cd   0/2     Pending
hello-r4vz7-deployment-c5d4b88f7-rr8cd   0/2     ContainerCreating
hello-r4vz7-deployment-c5d4b88f7-rr8cd   1/2     Running
hello-r4vz7-deployment-c5d4b88f7-rr8cd   2/2     Running
----

**We now have Knative Serving running!**
